### ISSUE TITLE
下载了楼主的爬虫，研究中。。。，谢谢分享

### ISSUE THREAD

**Issue by laugha** [zhegexiaohuozi/SeimiCrawler#1]
ConcurrentSkipListSet排重不合适吧，程序当掉重启后就无法排重了，还是持久化到磁盘更好？？

**Comment by zhegexiaohuozi** [comment]
其实小规模非生产环境使用的场景下使用内存去重还是使用本地文件区别不大，作为生产环境使用的话，肯定更要容易运维且水平扩展，这时候建议启用默认的基于redis的SeimiQueue实现，或是自行实现并接入其他成熟的数据存储系统。不过以后我也会考虑支持简易版的磁盘存储，只是不作为优先支持。

**Comment by laugha** [comment]
多谢，期待SeimiCrawler越来越好，使用中有问题再请教

**Comment by zhegexiaohuozi** [comment]
谢谢支持！
