### ISSUE TITLE
seimiagent不断崩溃

### ISSUE THREAD

**Issue by MorningDarkLi** [zhegexiaohuozi/SeimiCrawler#13]
使用seimiagent时解析2各层级的页面不断崩溃
![Uploading 1.png…]()
![Uploading 2.png…]()

**Comment by MorningDarkLi** [comment]
centos7.2，seimiagent1.3.0，报错信息
HttpConnection::writeResponse called while state is not 'SendingHeaders', not proceeding with sending headers.
SeimiAgent has crashed.
You can go to https://github.com/zhegexiaohuozi/SeimiAgent/issues and report a bug.
Such as your os version,app version,etc.
Segmentation fault

**Comment by MorningDarkLi** [comment]
出问题的url：
http://zc.open.qq.com/ListSku/view?firstCateId=100001
http://zc.open.qq.com/facilitator/details/10348.html

**Comment by zhenjun115** [comment]
the shortcut don't show @MorningDarkLi
