### ISSUE TITLE
Request 类中的 meta 能否变成 Map<String, Object>

### ISSUE THREAD

**Issue by ywjno** [zhegexiaohuozi/SeimiCrawler#14]
当我需要穿一个Long类型的值的时候，原来的 `Map<String, String>` 取值非常不方便，放值取值的时候都需要分别转换一次，而且这里看到并没特别处理，能否变量类型就直接改成 `Map<String, Object>`

**Comment by zhegexiaohuozi** [comment]
参考 https://github.com/zhegexiaohuozi/SeimiCrawler/pull/15
