### ISSUE TITLE
关于注解使用

### ISSUE THREAD

**Issue by CrazyShaQuiShi** [zhegexiaohuozi/SeimiCrawler#24]
```
       Seimi s = new Seimi();
         s.scan("com");
```

这个scan方法是设置扫描某个包下带有Crawler注解的意思吗？为什么我配置成com还是报
13:39:06 ERROR cn.wanghaomiao.seimi.core.Seimi - can not find any crawlers,please check!
难道只能扫描包名称是cn.wanghaomiao的包下的注解类吗？

**Comment by zhegexiaohuozi** [comment]
不是

**Comment by ycjnono** [comment]
"crawlers","queues","interceptors","cn.wanghaomiao.seimi",中间选一个
