### ISSUE TITLE
V2.0.0开发计划

### ISSUE THREAD

**Issue by zhegexiaohuozi** [zhegexiaohuozi/SeimiCrawler#25]
- 深度支持Spring boot，方便开发者进行更为有意思的尝试

**Comment by zhangweilun** [comment]
请问spring boot的分支现在可以用吗

**Comment by zhegexiaohuozi** [comment]
暂时还没完成



et.tw@163.com
 
发件人： willian
发送时间： 2018-01-15 11:24
收件人： zhegexiaohuozi/SeimiCrawler
抄送： xiaohuo; Assign
主题： Re: [zhegexiaohuozi/SeimiCrawler] V2.0.0开发计划 (#25)
请问spring boot的分支现在可以用吗
