### ISSUE TITLE
JsoupXpath在Maven库中找不到了

### ISSUE THREAD

**Issue by varlxj** [zhegexiaohuozi/SeimiCrawler#3]
JsoupXpath在几个大的Maven库中找不到了，404，最后还是翻到你项目中下载下来的

**Comment by kingwrcy** [comment]
同上,JsoupXpath-0.2.1.jar 找不到,最后在lib目录down了一个,为什么我还缺个org.jsoup的包,maven加上才好的.

**Comment by zhegexiaohuozi** [comment]
中央maven 库同步失败了，谢谢提醒，已经发起重新同步请求，我会继续跟进，再次感谢

**Comment by zhegexiaohuozi** [comment]
中央maven库已经正常。
