### ISSUE TITLE
CrawlerModel的startRequest方法，startRequests执行两次

### ISSUE THREAD

**Issue by xdrodger** [zhegexiaohuozi/SeimiCrawler#33]
用startRequest方式启动，startRequests获取了两次，望调整。
<img width="923" alt="issue" src="https://user-images.githubusercontent.com/12492402/48824072-24a1cf80-ed9e-11e8-8f77-e9bccb370929.png">

**Comment by zhegexiaohuozi** [comment]
没有获取两次，他们代表不同的用法

**Comment by xdrodger** [comment]
startRequests内如果是动态获取的，会造成浪费。startUrls获取后，保存局部变量，就不会有此问题

**Comment by zhegexiaohuozi** [comment]
可能你对他们用法有无解，startRequests又不是必须的，他只是给开发者提供一种可以提供复杂起始请求的方法。
