### ISSUE TITLE
startUrls如果爬取的网站的Url不正确，请问怎么捕获这个异常然后自己处理呢？

### ISSUE THREAD

**Issue by BUGBobo** [zhegexiaohuozi/SeimiCrawler#45]
在调用handleErrorRequest之前就已经抛出了四次异常，请问这个异常抛出之前能否自己捕获然后进行处理呢？

**Comment by zhegexiaohuozi** [comment]
文档：http://wiki.seimicrawler.org/#a849b0c550071525003d5ab6d9b8d1e0
![image](https://user-images.githubusercontent.com/2982325/56872774-3a0eda00-6a5f-11e9-8581-9d2d0d3a0587.png)

**Comment by BUGBobo** [comment]
我明白了，只能通过日志记录的方式来打印该异常，然后通过handleErrorRequest方法来实现自己的业务逻辑，并不能catch住异常。

**Comment by zhegexiaohuozi** [comment]
不是，你可以覆盖自定义实现，文档说的还不明白？

**Comment by zhegexiaohuozi** [comment]
记日志是默认的基本实现……

**Comment by BUGBobo** [comment]
嗯，我的意思就是默认的是只能记录日志，重写该方法的话可以实现自己的业务逻辑，但是日志是都会打印的。  我的意思是不能catch住异常不让他打印日志。

**Comment by zhegexiaohuozi** [comment]
覆盖后日志不会打印的

**Comment by zhegexiaohuozi** [comment]
覆盖后看你自己的实现

**Comment by BUGBobo** [comment]
![image](https://user-images.githubusercontent.com/23613077/56873287-e3f06580-6a63-11e9-9c29-07b693993e52.png)
会有异常信息抛出

**Comment by BUGBobo** [comment]
不好意思老师，我的意思可能表达错误了。
确实handleErrorRequest的日志不打印了，但是还会有异常信息抛出，我想问的问题是如何把这个异常信息catch住，不让他打印出来。

**Comment by zhegexiaohuozi** [comment]
这个不接受catch,是处理器扔出来的，你不想看日志，可以把处理器类的日志禁用
