### ISSUE TITLE
  @Autowired异常

### ISSUE THREAD

**Issue by chougaigai** [zhegexiaohuozi/SeimiCrawler#52]
在Crawler中使用@Autowired异常。
![image](https://user-images.githubusercontent.com/32348909/68960097-6bd46c00-080a-11ea-9eb5-e8249162d364.png)

**Comment by ljchengx** [comment]
怎么解决的？

**Comment by xzc-Eureka** [comment]
怎么解决的.........................????????????????

**Comment by chougaigai** [comment]
> 怎么解决的.........................????????????????

贴一下你的job代码
