### ISSUE TITLE
抓取头条这样不行吗

### ISSUE THREAD

**Issue by LyingDragons** [zhegexiaohuozi/SeimiCrawler#54]
![image](https://user-images.githubusercontent.com/45115465/71805346-f9149e00-30a0-11ea-857e-befea311e682.png)

**Comment by zhegexiaohuozi** [comment]
提取URL肯定没问题，但是你要考虑下你拿到的原始html是什么，这点很重要

**Comment by LyingDragons** [comment]
嗯  头条是页面是js
